name: Create release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      # - name: Build the TypeScript project
      #   run: |
      #     npm run build  # Ensure this runs 'tsc' to compile the project to 'dist'

      - name: List files to confirm dist directory
        run: |
          ls -la

      # - name: Check if dist directory exists
      #   run: |
      #     if [ -d "./dist" ]; then
      #       echo "Dist directory exists."
      #     else
      #       echo "Dist directory does not exist."
      #       exit 1
      #     fi

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Package the app
        run: |
          zip -r function.zip server.mjs

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name ChrisMcHardy --zip-file fileb://./function.zip